paths:
  raw: data/raw
  interim: data/interim
  processed: data/processed
market:
  bidding_zone: IE
  currency: EUR
  tz: Europe/Dublin
weather:
  lat: 53.4
  lon: -8.2
  height_m: 100
  use_cap_weighting: false
features:
  include_interconnectors: true
  include_fuels: false
train:
  start: '2025-08-15'
  end:   '2025-09-30'
  horizon_hours: 24
  model: xgb
  cv_splits: 12
